### ISSUE TITLE
[Bug] dbt unit tests break node searching

### ISSUE THREAD

**Issue by killian-dent** [nicholasyager/dagview#6]
### Description

Using a dbt manifest from a project that contains dbt unit tests causes the node selection search functionality to break.

### Steps to reproduce

1. Generate a dbt manifest that contains unit tests
2. Generate the powergraph hypergraph
3. Open browser and wait for full graph to render
4. Enter the name of a node and click "Select"
5. No visible change to the UI, full graph is still displayed
6. Dev tools console shows the error: `Uncaught TypeError:  Cannot read properties of undefined (reading 'name')`

![Screenshot 2024-09-05 at 2 33 24 PM](https://github.com/user-attachments/assets/fb51ed79-0ff9-4885-b444-bcd917772e07)
 
 ### Other observations

* The `Node` immediately preceding the console error shows an `id` of `unit_test.*` and the `node.data` value is `undefined`
* The following steps produce a successful result:
    * Remove the example unit test yaml files from the dbt project
    * Regenerate the project manifest
    * Regenerate the powergraph hypergraph
    * Re-open browser and let the new graph render
    * Enter the name of a node and click "Select"
    * The UI updates with the selected node

**Comment by nicholasyager** [comment]
Awesome find, @killian-dent! I have not tested this with `unit_test` resources yet, so it makes sense that this would be problematic. By default, `dagview` attempts to remove all tests, so my hunch here is that I should find a way to make note exclusion more accurate.

Let's see what I find!

**Comment by nicholasyager** [comment]
Yep, this was a rather straightforward issue to debug. I've pushed a fix that should eliminate this class of defect.
